[technote]
id = "rtn-047"
series_id = "RTN"
canonical_url = "https://rtn-047.lsst.io"
github_url = "https://github.com/lsst/rtn-047"
github_default_branch = "main"
date_created = 2022-05-01T00:00:00Z
organization.name = "NSF-DOE Vera C. Rubin Observatory"
organization.ror = "https://ror.org/048g3cy84"
license.id = "CC-BY-4.0"

[technote.status]
state = "stable"

[[technote.authors]]
internal_id = "guylp"
name = {given = "Leanne P.", family = "Guy"}
orcid = "https://orcid.org/0000-0003-0800-8755"